export const GET_HOME_USER_DATA_START = 'GET_HOME_USER_DATA_START';
export const GET_HOME_USER_DATA_SUCCESS = 'GET_HOME_USER_DATA_SUCCESS';
export const GET_HOME_USER_DATA_FAIL = 'GET_HOME_USER_DATA_FAIL';

export const HOME_KEY = 'home';
